package com.yaodingjiaoyu.datebase.pojo;
// Generated 2016-7-26 22:27:35 by Hibernate Tools 3.5.0.Final

/**
 * CampusPrice generated by hbm2java
 */
@SuppressWarnings("serial")
public class CampusPrice implements java.io.Serializable {

	private Integer PId;
	private CourseType courseType;
	private Campus campus;
	private int l1;
	private int l2;
	private int l3;
	private int l4;
	private int l5;
	private int l6;
	private int l7;
	private int l8;
	private int l9;
	private int l10;
	private int l11;
	private int l12;

	public CampusPrice() {
	}

	public CampusPrice(CourseType courseType, Campus campus, int l1, int l2, int l3, int l4, int l5, int l6, int l7,
			int l8, int l9, int l10, int l11, int l12) {
		this.courseType = courseType;
		this.campus = campus;
		this.l1 = l1;
		this.l2 = l2;
		this.l3 = l3;
		this.l4 = l4;
		this.l5 = l5;
		this.l6 = l6;
		this.l7 = l7;
		this.l8 = l8;
		this.l9 = l9;
		this.l10 = l10;
		this.l11 = l11;
		this.l12 = l12;
	}

	public Integer getPId() {
		return this.PId;
	}

	public void setPId(Integer PId) {
		this.PId = PId;
	}

	public CourseType getCourseType() {
		return this.courseType;
	}

	public void setCourseType(CourseType courseType) {
		this.courseType = courseType;
	}

	public Campus getCampus() {
		return this.campus;
	}

	public void setCampus(Campus campus) {
		this.campus = campus;
	}

	public int getL1() {
		return this.l1;
	}

	public void setL1(int l1) {
		this.l1 = l1;
	}

	public int getL2() {
		return this.l2;
	}

	public void setL2(int l2) {
		this.l2 = l2;
	}

	public int getL3() {
		return this.l3;
	}

	public void setL3(int l3) {
		this.l3 = l3;
	}

	public int getL4() {
		return this.l4;
	}

	public void setL4(int l4) {
		this.l4 = l4;
	}

	public int getL5() {
		return this.l5;
	}

	public void setL5(int l5) {
		this.l5 = l5;
	}

	public int getL6() {
		return this.l6;
	}

	public void setL6(int l6) {
		this.l6 = l6;
	}

	public int getL7() {
		return this.l7;
	}

	public void setL7(int l7) {
		this.l7 = l7;
	}

	public int getL8() {
		return this.l8;
	}

	public void setL8(int l8) {
		this.l8 = l8;
	}

	public int getL9() {
		return this.l9;
	}

	public void setL9(int l9) {
		this.l9 = l9;
	}

	public int getL10() {
		return this.l10;
	}

	public void setL10(int l10) {
		this.l10 = l10;
	}

	public int getL11() {
		return this.l11;
	}

	public void setL11(int l11) {
		this.l11 = l11;
	}

	public int getL12() {
		return this.l12;
	}

	public void setL12(int l12) {
		this.l12 = l12;
	}

}
