package com.yaodingjiaoyu.datebase.pojo;
// Generated 2016-7-26 22:27:35 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * CcContent generated by hbm2java
 */
@SuppressWarnings("serial")
public class CcContent implements java.io.Serializable {

	private Integer PId;
	private Examples examples;
	private Stuff stuff;
	private Campus campus;
	private Date insertTime;
	private String contents;

	public CcContent() {
	}

	public CcContent(Examples examples, Stuff stuff, Campus campus, Date insertTime, String contents) {
		this.examples = examples;
		this.stuff = stuff;
		this.campus = campus;
		this.insertTime = insertTime;
		this.contents = contents;
	}

	public Integer getPId() {
		return this.PId;
	}

	public void setPId(Integer PId) {
		this.PId = PId;
	}

	public Examples getExamples() {
		return this.examples;
	}

	public void setExamples(Examples examples) {
		this.examples = examples;
	}

	public Stuff getStuff() {
		return this.stuff;
	}

	public void setStuff(Stuff stuff) {
		this.stuff = stuff;
	}

	public Campus getCampus() {
		return this.campus;
	}

	public void setCampus(Campus campus) {
		this.campus = campus;
	}

	public Date getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

}
