package com.yaodingjiaoyu.datebase.pojo;
// Generated 2016-7-26 22:27:35 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ClassTime generated by hbm2java
 */
@SuppressWarnings("serial")
public class ClassTime implements java.io.Serializable {

	private Integer PId;
	private String classtime;
	private Set<ClassTable> classTables = new HashSet<ClassTable>(0);

	public ClassTime() {
	}

	public ClassTime(String classtime) {
		this.classtime = classtime;
	}

	public ClassTime(String classtime, Set<ClassTable> classTables) {
		this.classtime = classtime;
		this.classTables = classTables;
	}

	public Integer getPId() {
		return this.PId;
	}

	public void setPId(Integer PId) {
		this.PId = PId;
	}

	public String getClasstime() {
		return this.classtime;
	}

	public void setClasstime(String classtime) {
		this.classtime = classtime;
	}

	public Set<ClassTable> getClassTables() {
		return this.classTables;
	}

	public void setClassTables(Set<ClassTable> classTables) {
		this.classTables = classTables;
	}

}
