package com.yaodingjiaoyu.datebase.pojo;
// Generated 2016-7-26 22:27:35 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * CrPlan generated by hbm2java
 */
@SuppressWarnings("serial")
public class CrPlan implements java.io.Serializable {

	private Integer PId;
	private Student student;
	private Stuff stuff;
	private Campus campus;
	private Date planTime;
	private String content;
	private int status;

	public CrPlan() {
	}

	public CrPlan(Student student, Stuff stuff, Campus campus, Date planTime, String content, int status) {
		this.student = student;
		this.stuff = stuff;
		this.campus = campus;
		this.planTime = planTime;
		this.content = content;
		this.status = status;
	}

	public Integer getPId() {
		return this.PId;
	}

	public void setPId(Integer PId) {
		this.PId = PId;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Stuff getStuff() {
		return this.stuff;
	}

	public void setStuff(Stuff stuff) {
		this.stuff = stuff;
	}

	public Campus getCampus() {
		return this.campus;
	}

	public void setCampus(Campus campus) {
		this.campus = campus;
	}

	public Date getPlanTime() {
		return this.planTime;
	}

	public void setPlanTime(Date planTime) {
		this.planTime = planTime;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
