package com.yaodingjiaoyu.datebase.pojo;
// Generated 2016-8-25 16:42:37 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Hetong generated by hbm2java
 */
@SuppressWarnings("serial")
public class Hetong implements java.io.Serializable {

	private Integer PId;
	private Student student;
	private Stuff stuff;
	private CourseType courseType;
	private HtProperty htProperty;
	private Campus campus;
	private Level level;
	private Subject subject;
	private HetongType hetongType;
	private String hetongNum;
	private int normalHour;
	private double unitPrice;
	private double pos;
	private double cash;
	private String posNum;
	private String receiptNum;
	private Date signTime;
	private String remarks;
	private int status;

	public Hetong() {
	}

	public Hetong(Student student, Stuff stuff, CourseType courseType, HtProperty htProperty, Campus campus,
			Level level, Subject subject, HetongType hetongType, String hetongNum, int normalHour, double unitPrice,
			double pos, double cash, Date signTime, String remarks, int status) {
		this.student = student;
		this.stuff = stuff;
		this.courseType = courseType;
		this.htProperty = htProperty;
		this.campus = campus;
		this.level = level;
		this.subject = subject;
		this.hetongType = hetongType;
		this.hetongNum = hetongNum;
		this.normalHour = normalHour;
		this.unitPrice = unitPrice;
		this.pos = pos;
		this.cash = cash;
		this.signTime = signTime;
		this.remarks = remarks;
		this.status = status;
	}

	public Hetong(Student student, Stuff stuff, CourseType courseType, HtProperty htProperty, Campus campus,
			Level level, Subject subject, HetongType hetongType, String hetongNum, int normalHour, double unitPrice,
			double pos, double cash, String posNum, String receiptNum, Date signTime, String remarks, int status) {
		this.student = student;
		this.stuff = stuff;
		this.courseType = courseType;
		this.htProperty = htProperty;
		this.campus = campus;
		this.level = level;
		this.subject = subject;
		this.hetongType = hetongType;
		this.hetongNum = hetongNum;
		this.normalHour = normalHour;
		this.unitPrice = unitPrice;
		this.pos = pos;
		this.cash = cash;
		this.posNum = posNum;
		this.receiptNum = receiptNum;
		this.signTime = signTime;
		this.remarks = remarks;
		this.status = status;
	}

	public Integer getPId() {
		return this.PId;
	}

	public void setPId(Integer PId) {
		this.PId = PId;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Stuff getStuff() {
		return this.stuff;
	}

	public void setStuff(Stuff stuff) {
		this.stuff = stuff;
	}

	public CourseType getCourseType() {
		return this.courseType;
	}

	public void setCourseType(CourseType courseType) {
		this.courseType = courseType;
	}

	public HtProperty getHtProperty() {
		return this.htProperty;
	}

	public void setHtProperty(HtProperty htProperty) {
		this.htProperty = htProperty;
	}

	public Campus getCampus() {
		return this.campus;
	}

	public void setCampus(Campus campus) {
		this.campus = campus;
	}

	public Level getLevel() {
		return this.level;
	}

	public void setLevel(Level level) {
		this.level = level;
	}

	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public HetongType getHetongType() {
		return this.hetongType;
	}

	public void setHetongType(HetongType hetongType) {
		this.hetongType = hetongType;
	}

	public String getHetongNum() {
		return this.hetongNum;
	}

	public void setHetongNum(String hetongNum) {
		this.hetongNum = hetongNum;
	}

	public int getNormalHour() {
		return this.normalHour;
	}

	public void setNormalHour(int normalHour) {
		this.normalHour = normalHour;
	}

	public double getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(double unitPrice) {
		this.unitPrice = unitPrice;
	}

	public double getPos() {
		return this.pos;
	}

	public void setPos(double pos) {
		this.pos = pos;
	}

	public double getCash() {
		return this.cash;
	}

	public void setCash(double cash) {
		this.cash = cash;
	}

	public String getPosNum() {
		return this.posNum;
	}

	public void setPosNum(String posNum) {
		this.posNum = posNum;
	}

	public String getReceiptNum() {
		return this.receiptNum;
	}

	public void setReceiptNum(String receiptNum) {
		this.receiptNum = receiptNum;
	}

	public Date getSignTime() {
		return this.signTime;
	}

	public void setSignTime(Date signTime) {
		this.signTime = signTime;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
