package com.yaodingjiaoyu.datebase.pojo;
// Generated 2016-7-26 22:27:35 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
@SuppressWarnings("serial")
public class Student implements java.io.Serializable {

	private Integer PId;
	private Stuff stuff;
	private Campus campus;
	private Level level;
	private String name;
	private String sex;
	private Date birthday;
	private String school;
	private String phone1;
	private String phone2;
	private String address;
	private String parentName;
	private int status;
	private int allHour;
	private int lastHour;
	private int presentHour;
	private String username;
	private String password;
	private String power;
	private Date lastTime;
	private int nowClass;
	private Set<TestResult> testResults = new HashSet<TestResult>(0);
	private Set<ClassHour> classHours = new HashSet<ClassHour>(0);
	private Set<CrPlan> crPlans = new HashSet<CrPlan>(0);
	private Set<Hetong> hetongs = new HashSet<Hetong>(0);
	private Set<ClassContent> classContents = new HashSet<ClassContent>(0);
	private Set<ClassTable> classTables = new HashSet<ClassTable>(0);

	public Student() {
	}

	public Student(Campus campus, Level level, String name, String sex, Date birthday, String school, String address,
			String parentName, int status, int allHour, int lastHour, int presentHour, String username, String password,
			String power, Date lastTime, int nowClass) {
		this.campus = campus;
		this.level = level;
		this.name = name;
		this.sex = sex;
		this.birthday = birthday;
		this.school = school;
		this.address = address;
		this.parentName = parentName;
		this.status = status;
		this.allHour = allHour;
		this.lastHour = lastHour;
		this.presentHour = presentHour;
		this.username = username;
		this.password = password;
		this.power = power;
		this.lastTime = lastTime;
		this.nowClass = nowClass;
	}

	public Student(Stuff stuff, Campus campus, Level level, String name, String sex, Date birthday, String school,
			String phone1, String phone2, String address, String parentName, int status, int allHour, int lastHour,
			int presentHour, String username, String password, String power, Date lastTime, int nowClass,
			Set<TestResult> testResults, Set<ClassHour> classHours, Set<CrPlan> crPlans, Set<Hetong> hetongs, Set<ClassContent> classContents, Set<ClassTable> classTables) {
		this.stuff = stuff;
		this.campus = campus;
		this.level = level;
		this.name = name;
		this.sex = sex;
		this.birthday = birthday;
		this.school = school;
		this.phone1 = phone1;
		this.phone2 = phone2;
		this.address = address;
		this.parentName = parentName;
		this.status = status;
		this.allHour = allHour;
		this.lastHour = lastHour;
		this.presentHour = presentHour;
		this.username = username;
		this.password = password;
		this.power = power;
		this.lastTime = lastTime;
		this.nowClass = nowClass;
		this.testResults = testResults;
		this.classHours = classHours;
		this.crPlans = crPlans;
		this.hetongs = hetongs;
		this.classContents = classContents;
		this.classTables = classTables;
	}

	public Integer getPId() {
		return this.PId;
	}

	public void setPId(Integer PId) {
		this.PId = PId;
	}

	public Stuff getStuff() {
		return this.stuff;
	}

	public void setStuff(Stuff stuff) {
		this.stuff = stuff;
	}

	public Campus getCampus() {
		return this.campus;
	}

	public void setCampus(Campus campus) {
		this.campus = campus;
	}

	public Level getLevel() {
		return this.level;
	}

	public void setLevel(Level level) {
		this.level = level;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	public String getPhone1() {
		return this.phone1;
	}

	public void setPhone1(String phone1) {
		this.phone1 = phone1;
	}

	public String getPhone2() {
		return this.phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getParentName() {
		return this.parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getAllHour() {
		return this.allHour;
	}

	public void setAllHour(int allHour) {
		this.allHour = allHour;
	}

	public int getLastHour() {
		return this.lastHour;
	}

	public void setLastHour(int lastHour) {
		this.lastHour = lastHour;
	}

	public int getPresentHour() {
		return this.presentHour;
	}

	public void setPresentHour(int presentHour) {
		this.presentHour = presentHour;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPower() {
		return this.power;
	}

	public void setPower(String power) {
		this.power = power;
	}

	public Date getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(Date lastTime) {
		this.lastTime = lastTime;
	}

	public int getNowClass() {
		return this.nowClass;
	}

	public void setNowClass(int nowClass) {
		this.nowClass = nowClass;
	}

	public Set<TestResult> getTestResults() {
		return this.testResults;
	}

	public void setTestResults(Set<TestResult> testResults) {
		this.testResults = testResults;
	}

	public Set<ClassHour> getClassHours() {
		return this.classHours;
	}

	public void setClassHours(Set<ClassHour> classHours) {
		this.classHours = classHours;
	}

	public Set<CrPlan> getCrPlans() {
		return this.crPlans;
	}

	public void setCrPlans(Set<CrPlan> crPlans) {
		this.crPlans = crPlans;
	}

	public Set<Hetong> getHetongs() {
		return this.hetongs;
	}

	public void setHetongs(Set<Hetong> hetongs) {
		this.hetongs = hetongs;
	}

	public Set<ClassContent> getClassContents() {
		return this.classContents;
	}

	public void setClassContents(Set<ClassContent> classContents) {
		this.classContents = classContents;
	}

	public Set<ClassTable> getClassTables() {
		return this.classTables;
	}

	public void setClassTables(Set<ClassTable> classTables) {
		this.classTables = classTables;
	}

}
