package com.yaodingjiaoyu.datebase.pojo;
// Generated 2016-7-26 22:27:35 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Stuff generated by hbm2java
 */
@SuppressWarnings("serial")
public class Stuff implements java.io.Serializable {

	private Integer PId;
	private Job job;
	private Campus campus;
	private String name;
	private String sex;
	private String idCard;
	private String phone;
	private String address;
	private String jingjiPhone;
	private String username;
	private String password;
	private String power;
	private int status;
	private int partTime;
	private Set<CcPlan> ccPlans = new HashSet<CcPlan>(0);
	private Set<CrPlan> crPlans = new HashSet<CrPlan>(0);
	private Set<Student> students = new HashSet<Student>(0);
	private Set<ClassContent> classContents = new HashSet<ClassContent>(0);
	private Set<Examples> exampleses = new HashSet<Examples>(0);
	private Set<CcContent> ccContents = new HashSet<CcContent>(0);
	private Set<Hetong> hetongs = new HashSet<Hetong>(0);
	private Set<ClassTable> classTables = new HashSet<ClassTable>(0);

	public Stuff() {
	}

	public Stuff(Job job, Campus campus, String name, String sex, String idCard, String phone, String address,
			String jingjiPhone, String username, String password, String power, int status, int partTime) {
		this.job = job;
		this.campus = campus;
		this.name = name;
		this.sex = sex;
		this.idCard = idCard;
		this.phone = phone;
		this.address = address;
		this.jingjiPhone = jingjiPhone;
		this.username = username;
		this.password = password;
		this.power = power;
		this.status = status;
		this.partTime = partTime;
	}

	public Stuff(Job job, Campus campus, String name, String sex, String idCard, String phone, String address,
			String jingjiPhone, String username, String password, String power, int status, int partTime, Set<CcPlan> ccPlans,
			Set<CrPlan> crPlans, Set<Student> students, Set<ClassContent> classContents, Set<Examples> exampleses, Set<CcContent> ccContents, Set<Hetong> hetongs,
			Set<ClassTable> classTables) {
		this.job = job;
		this.campus = campus;
		this.name = name;
		this.sex = sex;
		this.idCard = idCard;
		this.phone = phone;
		this.address = address;
		this.jingjiPhone = jingjiPhone;
		this.username = username;
		this.password = password;
		this.power = power;
		this.status = status;
		this.partTime = partTime;
		this.ccPlans = ccPlans;
		this.crPlans = crPlans;
		this.students = students;
		this.classContents = classContents;
		this.exampleses = exampleses;
		this.ccContents = ccContents;
		this.hetongs = hetongs;
		this.classTables = classTables;
	}

	public Integer getPId() {
		return this.PId;
	}

	public void setPId(Integer PId) {
		this.PId = PId;
	}

	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	public Campus getCampus() {
		return this.campus;
	}

	public void setCampus(Campus campus) {
		this.campus = campus;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getJingjiPhone() {
		return this.jingjiPhone;
	}

	public void setJingjiPhone(String jingjiPhone) {
		this.jingjiPhone = jingjiPhone;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPower() {
		return this.power;
	}

	public void setPower(String power) {
		this.power = power;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getPartTime() {
		return this.partTime;
	}

	public void setPartTime(int partTime) {
		this.partTime = partTime;
	}

	public Set<CcPlan> getCcPlans() {
		return this.ccPlans;
	}

	public void setCcPlans(Set<CcPlan> ccPlans) {
		this.ccPlans = ccPlans;
	}

	public Set<CrPlan> getCrPlans() {
		return this.crPlans;
	}

	public void setCrPlans(Set<CrPlan> crPlans) {
		this.crPlans = crPlans;
	}

	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

	public Set<ClassContent> getClassContents() {
		return this.classContents;
	}

	public void setClassContents(Set<ClassContent> classContents) {
		this.classContents = classContents;
	}

	public Set<Examples> getExampleses() {
		return this.exampleses;
	}

	public void setExampleses(Set<Examples> exampleses) {
		this.exampleses = exampleses;
	}

	public Set<CcContent> getCcContents() {
		return this.ccContents;
	}

	public void setCcContents(Set<CcContent> ccContents) {
		this.ccContents = ccContents;
	}

	public Set<Hetong> getHetongs() {
		return this.hetongs;
	}

	public void setHetongs(Set<Hetong> hetongs) {
		this.hetongs = hetongs;
	}

	public Set<ClassTable> getClassTables() {
		return this.classTables;
	}

	public void setClassTables(Set<ClassTable> classTables) {
		this.classTables = classTables;
	}

}
