package com.yaodingjiaoyu.datebase.pojo;
// Generated 2016-7-26 22:27:35 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Subject generated by hbm2java
 */
@SuppressWarnings("serial")
public class Subject implements java.io.Serializable {

	private Integer PId;
	private String name;
	private Set<TestResult> testResults = new HashSet<TestResult>(0);
	private Set<Hetong> hetongs = new HashSet<Hetong>(0);
	private Set<ClassTable> classTables = new HashSet<ClassTable>(0);

	public Subject() {
	}

	public Subject(String name) {
		this.name = name;
	}

	public Subject(String name, Set<TestResult> testResults, Set<Hetong> hetongs, Set<ClassTable> classTables) {
		this.name = name;
		this.testResults = testResults;
		this.hetongs = hetongs;
		this.classTables = classTables;
	}

	public Integer getPId() {
		return this.PId;
	}

	public void setPId(Integer PId) {
		this.PId = PId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<TestResult> getTestResults() {
		return this.testResults;
	}

	public void setTestResults(Set<TestResult> testResults) {
		this.testResults = testResults;
	}

	public Set<Hetong> getHetongs() {
		return this.hetongs;
	}

	public void setHetongs(Set<Hetong> hetongs) {
		this.hetongs = hetongs;
	}

	public Set<ClassTable> getClassTables() {
		return this.classTables;
	}

	public void setClassTables(Set<ClassTable> classTables) {
		this.classTables = classTables;
	}

}
