package com.yaodingjiaoyu.datebase.pojo;
// Generated 2016-7-26 22:27:35 by Hibernate Tools 3.5.0.Final

/**
 * Suggest generated by hbm2java
 */
@SuppressWarnings("serial")
public class Suggest implements java.io.Serializable {

	private Integer PId;
	private ClassTable classTable;
	private Campus campus;
	private int pingfen;
	private String suggestion;

	public Suggest() {
	}

	public Suggest(ClassTable classTable, Campus campus, int pingfen, String suggestion) {
		this.classTable = classTable;
		this.campus = campus;
		this.pingfen = pingfen;
		this.suggestion = suggestion;
	}

	public Integer getPId() {
		return this.PId;
	}

	public void setPId(Integer PId) {
		this.PId = PId;
	}

	public ClassTable getClassTable() {
		return this.classTable;
	}

	public void setClassTable(ClassTable classTable) {
		this.classTable = classTable;
	}

	public Campus getCampus() {
		return this.campus;
	}

	public void setCampus(Campus campus) {
		this.campus = campus;
	}

	public int getPingfen() {
		return this.pingfen;
	}

	public void setPingfen(int pingfen) {
		this.pingfen = pingfen;
	}

	public String getSuggestion() {
		return this.suggestion;
	}

	public void setSuggestion(String suggestion) {
		this.suggestion = suggestion;
	}

}
